---
- name: Check risk appetite
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Confirm that you understand and accept the risks
      ansible.builtin.assert:
        that:
          - i_accept_the_risks | bool
        fail_msg: >
          You did NOT set i_accept_the_risks: true
          
          This playbook deploys an autonomous LLM agent (OpenClaw / clawdbot) with tool access 
          (shell commands, file system, network/browser capabilities, etc.).
          
          LLM agents can NEVER be made perfectly secure. Real risks include:
          - Prompt injection leading to arbitrary code execution
          - Accidental or malicious exposure of API keys, credentials, or sensitive data
          - Exploits through malicious plugins/skills from public hubs
          - Configuration mistakes leading to public exposure (this has happened to many users already)
          
          This playbook only applies basic hardening (Tailscale-only access, non-root user, UFW lockdown, etc.).
          It does NOT eliminate the fundamental agent risks.
          
          Only proceed if you fully understand these limitations and accept the risks.
          
          To continue, explicitly set in your vars or via extra-vars:
            i_accept_the_risks: true
          
          Otherwise: cancel now and read the security warnings first 
          (https://docs.openclaw.ai/security, community threads, etc.)
      delegate_to: 127.0.0.1

- name: Hardened OpenClaw VPS Deployment
  hosts: all
  become: yes

  tasks:
    - name: Update and Upgrade
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install essential tools
      apt:
        name: [curl, wget, ufw, fail2ban, ca-certificates, gnupg, git, unattended-upgrades]
        state: present

    - name: Create dedicated OpenClaw user
      user:
        name: "{{ item.name }}"
        shell: /bin/bash
        create_home: yes
        groups: "{{ item.groups }}"
        append: yes
        state: present
      loop:
        - name: "{{ new_admin }}"
          groups: sudo
        - name: "{{ new_user }}"
          groups: []

    - name: Enable User Lingering
      command: "loginctl enable-linger {{ new_user }}"

    - name: "4.Adapt sudoers: Make %sudo group passwordless:" 
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Set up SSH Key
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      loop:
        - "{{ new_admin }}"
        - "{{ new_user }}"

    - name: Hardened SSH Configuration (Port 2222)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#?Port ', line: "Port {{ ssh_port }}" }
        - { regexp: '^#?PermitRootLogin ', line: "PermitRootLogin no" }
        - { regexp: '^#?PasswordAuthentication ', line: "PasswordAuthentication no" }
      notify: Restart SSH

    - name: Firewall Elimination Diet
      ufw:
        state: enabled
        policy: deny
      tags: fw


    - name: Install NodeJS from Official Repo
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }}.x | bash -
        apt-get install -y nodejs

    - name: Install Tailscale
      shell: curl -fsSL https://tailscale.com/install.sh | sh

    - name: Authenticate Tailscale
      command: "tailscale up --authkey={{ tailscale_auth_key }}"
      ignore_errors: yes

    - name: Allow tailscale ipv4 ip's
      ufw:
        rule: allow
        from_ip: 100.64.0.0/10
        port: "{{ ssh_port }}"
        proto: tcp
      tags: fw

    - name: Manage public rule for ssh on 2222 
      ufw:
        rule: allow
        port: "{{ ssh_port }}"
        proto: tcp
        delete: "{{ not public_ssh_access | bool }}"
      tags: fw

    - name: Remove Public SSH Access
      ufw:
        rule: deny
        port: "{{ ssh_port }}"
        proto: tcp
        delete: "{{ public_ssh_access | bool }}"
      tags: fw

    - name: Install OpenClaw (Headless Mode)
      become_user: "{{ new_user }}"
      shell: |
        curl -fsSL https://openclaw.ai/install.sh | bash -s -- --no-prompt --no-onboard
      args:
        executable: /bin/bash
        creates: "/home/{{ new_user }}/.openclaw/bin/openclaw"

    - name: Get UID of {{ new_user }}
      ansible.builtin.getent:
        database: passwd
        key: "{{ new_user }}"
      tags: nono

    - name: Headless Onboarding via CLI
      become_user: "{{ new_user }}"
      shell: |
        export PATH=$PATH:/home/{{ new_user }}/.npm-global/bin
        # This bypasses the TUI wizard and sets the config directly
        openclaw onboard --non-interactive \
          --accept-risk \
          --auth-choice apiKey \
          --token-provider {{ llm_provider }} \
          --anthropic-api-key {{ llm_api_key }} \
          --install-daemon
      args:
        creates: "/home/{{ new_user }}/.openclaw/openclaw.json"
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[new_user][1] }}"

    - name: Install Telegram Provider Plugin
      become_user: "{{ new_user }}"
      shell: |
        export PATH=$PATH:/home/{{ new_user }}/.npm-global/bin
        openclaw plugins enable telegram
      args:
        executable: /bin/bash
        creates: "/home/{{ new_user }}/.openclaw/plugins/telegram"
      tags: channel

    - name: 13b. Register Telegram Channel
      become_user: "{{ new_user }}"
      shell: |
        export PATH=$PATH:/home/{{ new_user }}/.npm-global/bin
        openclaw channels add \
          --channel telegram \
          --token "{{ messaging_token }}" \
          --name "FortressBot"
      args:
        executable: /bin/bash
        # This prevents re-running if the channel is already configured in the JSON
        creates: "/home/{{ new_user }}/.openclaw/channels/telegram.json"
      tags: channel

    - name: Create tempdir
      when: 'use_nono | bool'
      tempfile:
       state: directory
      register: tempdir
      tags: nono

    - name: Download nono
      when: 'use_nono | bool'
      get_url:
        url: "{{ nono_distro.url }}"
        checksum: "{{ nono_distro.hash }}"
        dest: "{{ tempdir.path }}/nono-{{ nono_distro.hash[-6:] }}.tgz"
        force: false
      tags: nono

    - name: Unarchive nono
      when: 'use_nono | bool'
      unarchive:
        src: "{{ tempdir.path }}/nono-{{ nono_distro.hash[-6:] }}.tgz"
        dest: "{{ tempdir.path }}"
        remote_src: true
      tags: nono

    - name: Install nono
      when: 'use_nono | bool'
      copy:
        remote_src: true
        src: "{{ tempdir.path }}/nono"
        dest: "/usr/local/bin/nono-{{ nono_distro.hash[-6:] }}"
        mode: '755'
        force: false
      tags: nono

    - name: Create symlink nono
      when: 'use_nono | bool'
      file:
        state: link
        src: "/usr/local/bin/nono-{{ nono_distro.hash[-6:] }}"
        dest: "/usr/local/bin/nono"
        force: true
      tags: nono

    - name: Remove tempdir
      when: 'use_nono | bool'
      file:
        path: "{{ tempdir.path }}"
        state: absent
      tags: nono

    - name: Override unitfile
      when: 'use_nono | bool'
      copy:
        src: override.conf
        dest: /home/openclaw/.config/systemd/user/openclaw-gateway.service.d/
        mode: '644'
        owner: openclaw
        group: openclaw
      tags: nono

    - name: Revert unitfile override
      when: 'not use_nono | bool'
      become_user: "{{ new_user }}"
      command:
        argv:
          - systemctl
          - '--user'
          - revert
          - openclaw-gateway
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[new_user][1] }}"
      tags: nono

    - name: Ensure OpenClaw is running (User Scope)
      become: true
      become_user: "{{ new_user }}"
      ansible.builtin.systemd:
        name: openclaw-gateway
        scope: user
        state: started
        enabled: yes
        daemon_reload: yes
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[new_user][1] }}"
      tags: nono

    - name: Firewall - Allow all traffic from Tailscale interface
      become: true
      community.general.ufw:
        rule: allow
        direction: in
        interface: tailscale0
      tags: fw

  handlers:
    - name: Restart SSH
      service: name=ssh state=restarted
